# Experiment submission file
# Usage: condor_submit thisfile.sub
universe = vanilla
requirements = (OpSys == "LINUX") && ((OpSysMajorVer == 6) || (OpSysMajorVer == 7))
request_cpus = 1
request_memory = 1GB
request_disk = 512MB

executable = jobwrapper.sh
Python = build/Python-3.6.2-built.tar.gz
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $(Python), job.py

Description = r$(rule)_r$(n)_r$(z)
log = $(Description).chtc_log
error = $(Description).chtc_err
output = $(Description).chtc_out

arguments = $(rule) $(n) $(z)
queue rule, n, z from (
30, 5, 1
30, 5, 2
)
